### ISSUE TITLE
syntax error - react-bootstrap-typeahead/css/Typeahead

### ISSUE THREAD

**Issue by djberg96** [ManageIQ/manageiq-v2v#1138]
Courtesy of @NickLaMuro at https://github.com/ManageIQ/manageiq-v2v/pull/1134#issuecomment-660353779:

```
SassC::SyntaxError: Error: File to import not found or unreadable: react-bootstrap-typeahead/css/Typeahead.
        on line 7:1 of vendor/bundle/ruby/2.5.0/bundler/gems/manageiq-v2v-ee308b136335/app/assets/stylesheets/manageiq-v2v/type-ahead-select.scss
        from line 2:1 of vendor/bundle/ruby/2.5.0/bundler/gems/manageiq-v2v-ee308b136335/app/assets/stylesheets/manageiq-v2v/base.scss
>> @import 'react-bootstrap-typeahead/css/Typeahead';
   ^
/home/travis/build/ManageIQ/manageiq-cross_repo-tests/repos/ManageIQ/manageiq-ui-classic@a52dfd0baba3d9f4a4a9d84ea49bcf6cdacccdad/vendor/bundle/ruby/2.5.0/bundler/gems/manageiq-v2v-ee308b136335/app/assets/stylesheets/manageiq-v2v/type-ahead-select.scss:7
/home/travis/build/ManageIQ/manageiq-cross_repo-tests/repos/ManageIQ/manageiq-ui-classic@a52dfd0baba3d9f4a4a9d84ea49bcf6cdacccdad/vendor/bundle/ruby/2.5.0/gems/sassc-2.4.0/lib/sassc/engine.rb:50:in `render'
/home/travis/build/ManageIQ/manageiq-cross_repo-tests/repos/ManageIQ/manageiq-ui-classic@a52dfd0baba3d9f4a4a9d84ea49bcf6cdacccdad/vendor/bundle/ruby/2.5.0/gems/sassc-rails-2.1.2/lib/sassc/rails/template.rb:40:in `block in call'
/home/travis/build/ManageIQ/manageiq-cross_repo-tests/repos/ManageIQ/manageiq-ui-classic@a52dfd0baba3d9f4a4a9d84ea49bcf6cdacccdad/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/utils.rb:171:in `module_include'
/home/travis/build/ManageIQ/manageiq-cross_repo-tests/repos/ManageIQ/manageiq-ui-classic@a52dfd0baba3d9f4a4a9d84ea49bcf6cdacccdad/vendor/bundle/ruby/2.5.0/gems/sassc-rails-2.1.2/lib/sassc/rails/template.rb:39:in `call'
/home/travis/build/ManageIQ/manageiq-cross_repo-tests/repos/ManageIQ/manageiq-ui-classic@a52dfd0baba3d9f4a4a9d84ea49bcf6cdacccdad/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/sass_processor.rb:30:in `call'
/home/travis/build/ManageIQ/manageiq-cross_repo-tests/repos/ManageIQ/manageiq-ui-classic@a52dfd0baba3d9f4a4a9d84ea49bcf6cdacccdad/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:75:in `call_processor'
/home/travis/build/ManageIQ/manageiq-cross_repo-tests/repos/ManageIQ/manageiq-ui-classic@a52dfd0baba3d9f4a4a9d84ea49bcf6cdacccdad/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
/home/travis/build/ManageIQ/manageiq-cross_repo-tests/repos/ManageIQ/manageiq-ui-classic@a52dfd0baba3d9f4a4a9d84ea49bcf6cdacccdad/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:56:in `reverse_each'
/home/travis/build/ManageIQ/manageiq-cross_repo-tests/repos/ManageIQ/manageiq-ui-classic@a52dfd0baba3d9f4a4a9d84ea49bcf6cdacccdad/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:56:in `call_processors'
/home/travis/build/ManageIQ/manageiq-cross_repo-tests/repos/ManageIQ/manageiq-ui-classic@a52dfd0baba3d9f4a4a9d84ea49bcf6cdacccdad/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/loader.rb:134:in `load_from_unloaded'
/home/travis/build/ManageIQ/manageiq-cross_repo-tests/repos/ManageIQ/manageiq-ui-classic@a52dfd0baba3d9f4a4a9d84ea49bcf6cdacccdad/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/loader.rb:60:in `block in load'
/home/travis/build/ManageIQ/manageiq-cross_repo-tests/repos/ManageIQ/manageiq-ui-classic@a52dfd0baba3d9f4a4a9d84ea49bcf6cdacccdad/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
/home/travis/build/ManageIQ/manageiq-cross_repo-tests/repos/ManageIQ/manageiq-ui-classic@a52dfd0baba3d9f4a4a9d84ea49bcf6cdacccdad/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/loader.rb:44:in `load'
/home/travis/build/ManageIQ/manageiq-cross_repo-tests/repos/ManageIQ/manageiq-ui-classic@a52dfd0baba3d9f4a4a9d84ea49bcf6cdacccdad/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/cached_environment.rb:20:in `block in initialize'
/home/travis/build/ManageIQ/manageiq-cross_repo-tests/repos/ManageIQ/manageiq-ui-classic@a52dfd0baba3d9f4a4a9d84ea49bcf6cdacccdad/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/cached_environment.rb:47:in `load'
/home/travis/build/ManageIQ/manageiq-cross_repo-tests/repos/ManageIQ/manageiq-ui-classic@a52dfd0baba3d9f4a4a9d84ea49bcf6cdacccdad/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/bundle.rb:23:in `block in call'
/home/travis/build/ManageIQ/manageiq-cross_repo-tests/repos/ManageIQ/manageiq-ui-classic@a52dfd0baba3d9f4a4a9d84ea49bcf6cdacccdad/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/utils.rb:200:in `dfs'
/home/travis/build/ManageIQ/manageiq-cross_repo-tests/repos/ManageIQ/manageiq-ui-classic@a52dfd0baba3d9f4a4a9d84ea49bcf6cdacccdad/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/bundle.rb:24:in `call'
/home/travis/build/ManageIQ/manageiq-cross_repo-tests/repos/ManageIQ/manageiq-ui-classic@a52dfd0baba3d9f4a4a9d84ea49bcf6cdacccdad/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:75:in `call_processor'
/home/travis/build/ManageIQ/manageiq-cross_repo-tests/repos/ManageIQ/manageiq-ui-classic@a52dfd0baba3d9f4a4a9d84ea49bcf6cdacccdad/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
/home/travis/build/ManageIQ/manageiq-cross_repo-tests/repos/ManageIQ/manageiq-ui-classic@a52dfd0baba3d9f4a4a9d84ea49bcf6cdacccdad/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:56:in `reverse_each'
/home/travis/build/ManageIQ/manageiq-cross_repo-tests/repos/ManageIQ/manageiq-ui-classic@a52dfd0baba3d9f4a4a9d84ea49bcf6cdacccdad/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:56:in `call_processors'
/home/travis/build/ManageIQ/manageiq-cross_repo-tests/repos/ManageIQ/manageiq-ui-classic@a52dfd0baba3d9f4a4a9d84ea49bcf6cdacccdad/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/loader.rb:134:in `load_from_unloaded'
/home/travis/build/ManageIQ/manageiq-cross_repo-tests/repos/ManageIQ/manageiq-ui-classic@a52dfd0baba3d9f4a4a9d84ea49bcf6cdacccdad/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/loader.rb:60:in `block in load'
/home/travis/build/ManageIQ/manageiq-cross_repo-tests/repos/ManageIQ/manageiq-ui-classic@a52dfd0baba3d9f4a4a9d84ea49bcf6cdacccdad/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
/home/travis/build/ManageIQ/manageiq-cross_repo-tests/repos/ManageIQ/manageiq-ui-classic@a52dfd0baba3d9f4a4a9d84ea49bcf6cdacccdad/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/loader.rb:44:in `load'
/home/travis/build/ManageIQ/manageiq-cross_repo-tests/repos/ManageIQ/manageiq-ui-classic@a52dfd0baba3d9f4a4a9d84ea49bcf6cdacccdad/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/cached_environment.rb:20:in `block in initialize'
/home/travis/build/ManageIQ/manageiq-cross_repo-tests/repos/ManageIQ/manageiq-ui-classic@a52dfd0baba3d9f4a4a9d84ea49bcf6cdacccdad/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/cached_environment.rb:47:in `load'
/home/travis/build/ManageIQ/manageiq-cross_repo-tests/repos/ManageIQ/manageiq-ui-classic@a52dfd0baba3d9f4a4a9d84ea49bcf6cdacccdad/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/base.rb:66:in `find_asset'
/home/travis/build/ManageIQ/manageiq-cross_repo-tests/repos/ManageIQ/manageiq-ui-classic@a52dfd0baba3d9f4a4a9d84ea49bcf6cdacccdad/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/base.rb:73:in `find_all_linked_assets'
/home/travis/build/ManageIQ/manageiq-cross_repo-tests/repos/ManageIQ/manageiq-ui-classic@a52dfd0baba3d9f4a4a9d84ea49bcf6cdacccdad/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/manifest.rb:142:in `block in find'
/home/travis/build/ManageIQ/manageiq-cross_repo-tests/repos/ManageIQ/manageiq-ui-classic@a52dfd0baba3d9f4a4a9d84ea49bcf6cdacccdad/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/legacy.rb:114:in `block (2 levels) in logical_paths'
/home/travis/build/ManageIQ/manageiq-cross_repo-tests/repos/ManageIQ/manageiq-ui-classic@a52dfd0baba3d9f4a4a9d84ea49bcf6cdacccdad/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/path_utils.rb:228:in `block in stat_tree'
/home/travis/build/ManageIQ/manageiq-cross_repo-tests/repos/ManageIQ/manageiq-ui-classic@a52dfd0baba3d9f4a4a9d84ea49bcf6cdacccdad/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/path_utils.rb:212:in `block in stat_directory'
/home/travis/build/ManageIQ/manageiq-cross_repo-tests/repos/ManageIQ/manageiq-ui-classic@a52dfd0baba3d9f4a4a9d84ea49bcf6cdacccdad/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/path_utils.rb:209:in `each'
/home/travis/build/ManageIQ/manageiq-cross_repo-tests/repos/ManageIQ/manageiq-ui-classic@a52dfd0baba3d9f4a4a9d84ea49bcf6cdacccdad/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/path_utils.rb:209:in `stat_directory'
/home/travis/build/ManageIQ/manageiq-cross_repo-tests/repos/ManageIQ/manageiq-ui-classic@a52dfd0baba3d9f4a4a9d84ea49bcf6cdacccdad/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/path_utils.rb:227:in `stat_tree'
/home/travis/build/ManageIQ/manageiq-cross_repo-tests/repos/ManageIQ/manageiq-ui-classic@a52dfd0baba3d9f4a4a9d84ea49bcf6cdacccdad/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/path_utils.rb:231:in `block in stat_tree'
/home/travis/build/ManageIQ/manageiq-cross_repo-tests/repos/ManageIQ/manageiq-ui-classic@a52dfd0baba3d9f4a4a9d84ea49bcf6cdacccdad/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/path_utils.rb:212:in `block in stat_directory'
/home/travis/build/ManageIQ/manageiq-cross_repo-tests/repos/ManageIQ/manageiq-ui-classic@a52dfd0baba3d9f4a4a9d84ea49bcf6cdacccdad/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/path_utils.rb:209:in `each'
/home/travis/build/ManageIQ/manageiq-cross_repo-tests/repos/ManageIQ/manageiq-ui-classic@a52dfd0baba3d9f4a4a9d84ea49bcf6cdacccdad/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/path_utils.rb:209:in `stat_directory'
/home/travis/build/ManageIQ/manageiq-cross_repo-tests/repos/ManageIQ/manageiq-ui-classic@a52dfd0baba3d9f4a4a9d84ea49bcf6cdacccdad/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/path_utils.rb:227:in `stat_tree'
/home/travis/build/ManageIQ/manageiq-cross_repo-tests/repos/ManageIQ/manageiq-ui-classic@a52dfd0baba3d9f4a4a9d84ea49bcf6cdacccdad/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/legacy.rb:105:in `each'
/home/travis/build/ManageIQ/manageiq-cross_repo-tests/repos/ManageIQ/manageiq-ui-classic@a52dfd0baba3d9f4a4a9d84ea49bcf6cdacccdad/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/legacy.rb:105:in `block in logical_paths'
/home/travis/build/ManageIQ/manageiq-cross_repo-tests/repos/ManageIQ/manageiq-ui-classic@a52dfd0baba3d9f4a4a9d84ea49bcf6cdacccdad/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/legacy.rb:104:in `each'
/home/travis/build/ManageIQ/manageiq-cross_repo-tests/repos/ManageIQ/manageiq-ui-classic@a52dfd0baba3d9f4a4a9d84ea49bcf6cdacccdad/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/legacy.rb:104:in `logical_paths'
/home/travis/build/ManageIQ/manageiq-cross_repo-tests/repos/ManageIQ/manageiq-ui-classic@a52dfd0baba3d9f4a4a9d84ea49bcf6cdacccdad/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/manifest.rb:140:in `find'
/home/travis/build/ManageIQ/manageiq-cross_repo-tests/repos/ManageIQ/manageiq-ui-classic@a52dfd0baba3d9f4a4a9d84ea49bcf6cdacccdad/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/manifest.rb:186:in `compile'
/home/travis/build/ManageIQ/manageiq-cross_repo-tests/repos/ManageIQ/manageiq-ui-classic@a52dfd0baba3d9f4a4a9d84ea49bcf6cdacccdad/vendor/bundle/ruby/2.5.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/task.rb:68:in `block (3 levels) in define'
/home/travis/build/ManageIQ/manageiq-cross_repo-tests/repos/ManageIQ/manageiq-ui-classic@a52dfd0baba3d9f4a4a9d84ea49bcf6cdacccdad/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/rake/sprocketstask.rb:147:in `with_logger'
/home/travis/build/ManageIQ/manageiq-cross_repo-tests/repos/ManageIQ/manageiq-ui-classic@a52dfd0baba3d9f4a4a9d84ea49bcf6cdacccdad/vendor/bundle/ruby/2.5.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/task.rb:67:in `block (2 levels) in define'
/home/travis/build/ManageIQ/manageiq-cross_repo-tests/repos/ManageIQ/manageiq@6e36a353f20852092882fbc866e23341196e1c85/lib/tasks/evm.rake:115:in `block (4 levels) in <top (required)>'
/home/travis/build/ManageIQ/manageiq-cross_repo-tests/repos/ManageIQ/manageiq@6e36a353f20852092882fbc866e23341196e1c85/lib/tasks/evm_rake_helper.rb:7:in `with_dummy_database_url_configuration'
/home/travis/build/ManageIQ/manageiq-cross_repo-tests/repos/ManageIQ/manageiq@6e36a353f20852092882fbc866e23341196e1c85/lib/tasks/evm.rake:113:in `block (3 levels) in <top (required)>'
/home/travis/build/ManageIQ/manageiq-cross_repo-tests/repos/ManageIQ/manageiq@6e36a353f20852092882fbc866e23341196e1c85/lib/tasks/integration.rake:15:in `block (3 levels) in <top (required)>'
/home/travis/build/ManageIQ/manageiq-cross_repo-tests/repos/ManageIQ/manageiq-ui-classic@a52dfd0baba3d9f4a4a9d84ea49bcf6cdacccdad/lib/tasks/manageiq/cypress.rake:11:in `block (3 levels) in <top (required)>'
/home/travis/build/ManageIQ/manageiq-cross_repo-tests/repos/ManageIQ/manageiq-ui-classic@a52dfd0baba3d9f4a4a9d84ea49bcf6cdacccdad/vendor/bundle/ruby/2.5.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
/home/travis/build/ManageIQ/manageiq-cross_repo-tests/repos/ManageIQ/manageiq-ui-classic@a52dfd0baba3d9f4a4a9d84ea49bcf6cdacccdad/vendor/bundle/ruby/2.5.0/bin/ruby_executable_hooks:24:in `eval'
/home/travis/build/ManageIQ/manageiq-cross_repo-tests/repos/ManageIQ/manageiq-ui-classic@a52dfd0baba3d9f4a4a9d84ea49bcf6cdacccdad/vendor/bundle/ruby/2.5.0/bin/ruby_executable_hooks:24:in `<main>'
Tasks: TOP => app:assets:precompile
```

**Comment by NickLaMuro** [comment]
As I currently can't replicate, and I think a lot of what I was seeing on CI was because of `node` version mismatches, I think this is a false positive.

Will report back when I get https://github.com/ManageIQ/manageiq-cross_repo/pull/64 working, and if that is working fine without needing to change anything.

**Comment by djberg96** [comment]
@NickLaMuro Ok, closing for now. If you change your mind later let me know and I'll reopen.
